### ISSUE TITLE
Fails to parse if closing tag is seperated by new-line

### ISSUE THREAD

**Issue by lasse16** [lomirus/html_editor#1]
I came across this issue while working with version 0.3.0.

On a website, there was an `<a>` that was closed by `<\a\n>`. The parser failed with the error message `"<a> does not match the </a\n>"`. 

To reproduce, attempt to parse the following segment
```html
<a> example </a
>
```

Firefox can parse the website regardless of that formatting error.
Quick workaround could be to just delete all newlines in the string?

**Comment by lomirus** [comment]
Thanks for your feedback and I am very glad to see the first issue of this project.

Now it's just been fixed in the latest master branch, and I think I will release the new version with some new features soon. So you can now try to add it by git if you want before the new version is released.

**Comment by lasse16** [comment]
Thank you for the quick response and fix 👍
