### ISSUE TITLE
Query by #id containing periods do not works

### ISSUE THREAD

**Issue by franksouza183** [lomirus/html_editor#12]
We can't match when querying by id contains periods:

```
let html = r#"<div id="foo.bar">baz</div>"#;
let nodes = parse(&html)?;
let selector = Selector::from("#foo.bar");
let element = nodes.query(&selector);

println!("{:?}", element);
// None
```

**Comment by lomirus** [comment]
It's as expected, because `#foo.bar` should be parsed for tags like `<div id="foo" class="bar">`.

You can try the code below and save it as `index.html`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
    <div id="foo.bar"></div>
    <script>
      const element = document.querySelector('#foo.bar')
      console.log(element)
    </script>
</body>
</html>
```

The output should be `null` in browser.

**Comment by franksouza183** [comment]
You're absolutely right. I feel dumb xD, for a brief moment I forgot how css selectors works, this is a case of invalid id attribute of the html file I'm parsing.
