### ISSUE TITLE
A function to replace a Node with a different Node or Vec<Node>

### ISSUE THREAD

**Issue by louis1001** [lomirus/html_editor#13]
I'd like to have a way of replacing a `Node` with something else. Similar to JavaScript's [`replaceWith`](https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceWith) or BeautifulSoup's [`replace_with`](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#replace-with).

**Comment by lomirus** [comment]
Just solved this issue by adding `replace_with()`. You can try the master branch in your project and feedback if it has problems.
