### ISSUE TITLE
Add pase html with some err

### ISSUE THREAD

**Issue by olehbozhok** [lomirus/html_editor#2]
It woild be great if add html with some err.
Like this 
```
 <!doctype html>
        <html lang="en">
            <head>
                <meta charset="utf-8">
                <title>Html parser</title>
            </head>
            <body>
                <h1 id="a" class="b c">Hello world</h1>
                <!-- comments & dangling elements are ignored -->
                <a class="trait" href="next/next2/">Queryable 

            </body>
        </html>
```

Because browser handle it.
I`m trying write crawler and use you parser, but got err on parse.. =-(

**Comment by lomirus** [comment]
I am not sure if it's against the simple precept of this project, but it's a useful feature indeed. I think I can add a new function `try_parse()` to handle such illegal html codes, which may take me at least a few days since I am not too available now.

**Comment by olehbozhok** [comment]
I would be very appreciate if you implement this feature.

**Comment by lomirus** [comment]
In fact I have added this feature in the master branch and you can try it now. The new stable version will be released after I implement the XML parsing.

**Comment by lomirus** [comment]
Added `try_parse()` in v0.5.0
